### ISSUE TITLE
Better mobile design

### ISSUE THREAD

**Issue by ujh** [ujh/fountainpencompanion#1343]
Many users use the site on smaller devices (phones or tablets) and in those cases the table layouts aren't ideal. Especially on a phone having to scroll sideways to get to the buttons is not fun, at all. This is why the currently inked section has a special design for smaller screen to make that easier. However, the pens, private inks, and public inks sections do not have that, yet.

At this point it is not clear to me how that all would work nicely, but it would be make the site easier to use for users on smaller screens.

**Comment by ujh** [comment]
I see. So let the user decide what option to use. That is a good idea.

**Comment by wkillerud** [comment]
I did some sketching on a potential card layout for inks and pens, with some minor tweaks also for Currently Inked in order to match.

https://codesandbox.io/s/sad-lake-dhflgs?file=/src/App.js

The design brings most of the content to a single column. This way the text content can grow vertically without things looking unbalanced.

```
Single-column layout avoids this problem 👇

swab    content
swab    content
        content
        content
        content
        content
        content
        content
```

I also wanted to reduce the number of `label: data` pairs, like `Swabbed: yes`. So I suggest a design where the _presence_ of a green badge equals the green checkmark of the table layout, and its _absence_ equals the grey X. The private-flag and custom tags are also represented with badges.

There's still a lot going on in the second card in the demo (with maximum content). We could choose to hide comments in the list view on mobile as well.

**Comment by ujh** [comment]
Very cool! That is already much better than what it was before!

**Comment by wkillerud** [comment]
Glad to hear that 😃 I can look into implementing it and tweak the design as I go if needed.

It's probably best to break this down in steps and do one table at a time. Maybe the Collected inks table first?

**Comment by ujh** [comment]
Yes, the inks should be fine, as there's a search for it. The pens part should probably be kept like it is until we get around to turning that into a React app, too.

**Comment by wkillerud** [comment]
I see the Pens section is a React app now (#1455). Want me to add a similar card layout, like in Inks?

**Comment by ujh** [comment]
Yes, that was the plan. And the search isn't there either, etc. I just haven't gotten around to doing any of them.

The "grand plan" here would be that all sections have feature parity. I haven't touched the currently inked section yet, but that is also something I want to do.
