### ISSUE TITLE
Attributes for a fountain pen

### ISSUE THREAD

**Issue by bmp** [ujh/fountainpencompanion#2073]
Is there any interest to add other columns to the fountain pens? For example, I'd like to have material, date that it was bought on, price, filling system, and potentially nib colour and trims. 

If there is an interest, I'd be happy to help with trying to contribute too.

**Comment by ujh** [comment]
Hi,

yes those were never added in the past because the table layout wasn't really flexible and it all just got too wide. Now that columns can be hidden (those without any content are actually hidden by default) and we have the card view (for mobile) that's not that much of a problem anymore.

That said, I'd still like to be a bit careful and not add _everything_. There is a comment field, which is essentially the escape hatch for all of the additional information.

Let's maybe discuss which additional columns make general sense and which don't. For example, there's already an "added on" column and I wonder if we could just repurpose this to be the "bought on" column by making it editable.

**Comment by bmp** [comment]
> That said, I'd still like to be a bit careful and not add _everything_. There is a comment field, which is essentially the escape hatch for all of the additional information.

Agreed, overkill of columns is no fun either! I wen't overboard I think with what I tried to [cobble](https://github.com/bmp/flock) together quickly.

> Let's maybe discuss which additional columns make general sense and which don't. For example, there's already an "added on" column and I wonder if we could just repurpose this to be the "bought on" column by making it editable.

Yes, that would work! I guess for me **key columns** in addition to the existing would be,
1. Material of the pen 
2. Filling system. 
3. Price

I can live without, 
1. Trims

Non-essential or through the comments (this is mostly because I constantly mix/match and change nibs),
1. Nib colour
2. Nib size (5mm, 6mm, 10mm, etc)
3. Nib type (UEF, EF, F, etc.)
But other folks might like Nib type included as it is currently included.

**Comment by ujh** [comment]
I would exclude the nib topic for now. I usually just edit the "nib" field whenever I switch them around, which I do a lot. One of the hidden features of the system is that when you've archived a currently inked entry, then that keeps track of the nib, too. I guess it would be useful to explain this (and many other things) somewhere on the site. Some day nibs could be their own entity in the system, instead of just a string, but that would be a big topic in itself.

As to the other columns, maybe we should discuss two separate categories:

1. Columns that will help with the clustering
2. Other columns

For no. 1 I think what's relevant is:

1. Brand (already exists)
2. Model (already exists)
3. Color / Material (I wonder if we need to separate those?)
4. Trim color (might overlap with no. 3 above)

I do now wonder if we really need to add more columns, or if it's actually enough as it is. I can identify my "TWSBI Eco yellow" just fine, or my "Leonardo Momento Zero XYZ with gold trim". The problem with additional columns is that not everyone uses them and we'll still have to cluster those entries that do not add the additional data somehow. On the other hand, having this data split out into separate columns will make it easier for at least those cases. 🤔 So maybe the full set of columns for now and the think of the rest later?

For no. 2:

1. Price
2. Filling system

**Comment by bmp** [comment]
> I would exclude the nib topic for now. I usually just edit the "nib" field whenever I switch them around, which I do a lot. One of the hidden features of the system is that when you've archived a currently inked entry, then that keeps track of the nib, too. I guess it would be useful to explain this (and many other things) somewhere on the site. Some day nibs could be their own entity in the system, instead of just a string, but that would be a big topic in itself.
> 
> As to the other columns, maybe we should discuss two separate categories:
> 
>     1. Columns that will help with the clustering
> 
>     2. Other columns
> 

Makes sense

> 
> For no. 1 I think what's relevant is:
> 
>     1. Brand (already exists)
> 
>     2. Model (already exists)
> 
>     3. Color / Material (I wonder if we need to separate those?)

These are not interchangeable attributes right? The reason I say this is, there can be a black ebonite and acrylic pen, but there is also a blue ebonite and a red acrylic too. So it would be hard to combine this together. And based on the comment at https://github.com/ujh/fountainpencompanion/issues/2072#issuecomment-1986886804, it is possible to cluster them in this manner too. I often check my pens by material or sometimes I want to check all non-black pens.

> 
>     4. Trim color (might overlap with no. 3 above)
> 
> 
> I do now wonder if we really need to add more columns, or if it's actually enough as it is. I can identify my "TWSBI Eco yellow" just fine, or my "Leonardo Momento Zero XYZ with gold trim". The problem with additional columns is that not everyone uses them and we'll still have to cluster those entries that do not add the additional data somehow. On the other hand, having this data split out into separate columns will make it easier for at least those cases. 🤔 So maybe the full set of columns for now and the think of the rest later?

It could be optional columns to begin with, as the pen list is populated, it could then allow for a drop down list which is populated by the models/pens already as we are discussing in the other thread/issue.

> 
> For no. 2:
> 
>     1. Price
Either keep it currency agnostic (one unitary number in user's choice of currency) or enforce a currency and then display according to user's choice of currency. I think the simpler option is to keep it currency agnostic

> 
>     2. Filling system

This is a fairly small set of a dozen or so filling systems.
