### ISSUE TITLE
Look into upgrading Twitter bootstrap

### ISSUE THREAD

**Issue by ujh** [ujh/fountainpencompanion#410]
Either that or replace it with something more modern like Tailwind.

**Comment by wkillerud** [comment]
Did you decide whether to upgrade Bootstrap or pursue a different option @ujh?

The reason I ask is I began tinkering with the [first small steps of an upgrade](https://github.com/wkillerud/fountainpencompanion/commit/abc161cbe353a973bd776a1733c83bbf8af74201) here the other day. It looks like it will be a _piece of work_ though [^1][^2], so if you've decided to go in a different direction I won't spend any more time on it 😄 Otherwise I'd be happy to help.

---

[^1]: https://getbootstrap.com/docs/4.0/migration/
[^2]: https://getbootstrap.com/docs/5.0/migration/

**Comment by ujh** [comment]
I would be happy for any kind of help! 💚 The design is currently not on my mind so you are free to do whatever you think will work.

**Comment by wkillerud** [comment]
Allright :smile: I'll keep tinkering then! 

It will _probably_ be a little while before I reach anything stable (holiday season coming up,  "unknown unknowns" for the upgrade), but feel free to ping me if you want to check in on the status in January.
